sudo: require
language: generic
services:
    - docker

before_install:
    - docker build -t alarsonebates/docker-react -f Dockerfile.dev . 

script:
    - docker run -e CI=true alarsonebates/docker-react npm run test -- --converage